minierp/Models/odbiorca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minierp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odbiorca
    {
        public decimal odbiorca_id { get; set; }
        public string nazwa { get; set; }
        public string powiat { get; set; }
        public string gmina { get; set; }
        public string kodpoczt { get; set; }
        public string miasto { get; set; }
        public string poczta { get; set; }
        public string ulica { get; set; }
        public string nrdomu { get; set; }
        public Nullable<decimal> rabat { get; set; }
    }
}

minierp/Models/odbiorcy.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minierp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class odbiorcy : DbContext
    {
        public odbiorcy()
            : base("name=odbiorcy")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<odbiorca> odbiorca { get; set; }
    }
}

minierp/Models/odbiorcy.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Konrad\source\repos\minierp\minierp\Models\odbiorcy.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

minierp/Models/odbiorcy.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

minierp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace minierp.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

minierp/Controllers/odbiorcyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using minierp.Models;

namespace minierp.Controllers
{
    public class odbiorcyController : Controller
    {
        private odbiorcy db = new odbiorcy();

        // GET: odbiorcy
        public ActionResult Index()
        {
            return View(db.odbiorca.ToList());
        }

        // GET: odbiorcy/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }

        // GET: odbiorcy/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: odbiorcy/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "odbiorca_id,nazwa,powiat,gmina,kodpoczt,miasto,poczta,ulica,nrdomu,rabat")] odbiorca odbiorca)
        {
            if (ModelState.IsValid)
            {
                db.odbiorca.Add(odbiorca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(odbiorca);
        }

        // GET: odbiorcy/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }

        // POST: odbiorcy/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "odbiorca_id,nazwa,powiat,gmina,kodpoczt,miasto,poczta,ulica,nrdomu,rabat")] odbiorca odbiorca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(odbiorca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(odbiorca);
        }

        // GET: odbiorcy/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            odbiorca odbiorca = db.odbiorca.Find(id);
            if (odbiorca == null)
            {
                return HttpNotFound();
            }
            return View(odbiorca);
        }

        // POST: odbiorcy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            odbiorca odbiorca = db.odbiorca.Find(id);
            db.odbiorca.Remove(odbiorca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

minierp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>miniERP</h2>

<h1 class=" text-center ">
    <div>
        <button type="button" class="btn btn-primary btn-lg btn-block"> @Html.ActionLink("Lista odbiorców", "Index", "odbiorcy",new {@style="color:#ffffff;" }, new {@style="color:#ffffff;" }) </button>
        <button type="button" class="btn btn-primary btn-lg btn-block"> @Html.ActionLink("Dodaj nowego odbiorcę", "Create", "odbiorcy",new {@style="color:#ffffff;" }, new {@style="color:#ffffff;" }) </button>
    </div>
</h1>

@using (Html.BeginForm("Index", "Home"))
{
}

minierp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>miniERP</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Lista odbiorców", "Index", "odbiorcy", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Dodaj nowego odbiorcę", "Create", "odbiorcy", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - miniERP</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

minierp/Views/odbiorcy/Create.cshtml
@model minierp.Models.odbiorca

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>odbiorca</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.powiat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.powiat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.powiat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gmina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gmina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gmina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kodpoczt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kodpoczt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kodpoczt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miasto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.poczta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.poczta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.poczta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nrdomu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nrdomu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nrdomu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rabat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rabat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rabat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

minierp/Views/odbiorcy/Delete.cshtml
@model minierp.Models.odbiorca

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>odbiorca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.powiat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.powiat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gmina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gmina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kodpoczt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kodpoczt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.miasto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.miasto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.poczta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.poczta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ulica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ulica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nrdomu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nrdomu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rabat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rabat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

minierp/Views/odbiorcy/Details.cshtml
@model minierp.Models.odbiorca

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>odbiorca</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nazwa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nazwa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.powiat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.powiat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gmina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gmina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.kodpoczt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.kodpoczt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.miasto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.miasto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.poczta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.poczta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ulica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ulica)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nrdomu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nrdomu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rabat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rabat)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.odbiorca_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

minierp/Views/odbiorcy/Edit.cshtml
@model minierp.Models.odbiorca

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>odbiorca</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.odbiorca_id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.powiat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.powiat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.powiat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gmina, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gmina, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gmina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kodpoczt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kodpoczt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kodpoczt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miasto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miasto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miasto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.poczta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.poczta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.poczta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nrdomu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nrdomu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nrdomu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rabat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rabat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rabat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

minierp/Views/odbiorcy/Index.cshtml
@model IEnumerable<minierp.Models.odbiorca>

@{
    ViewBag.Title = "Index";
}

<p>
    @Html.ActionLink("Dodaj odbiorcę", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nazwa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.powiat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gmina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.kodpoczt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.miasto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.poczta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ulica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nrdomu)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rabat)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nazwa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.powiat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gmina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.kodpoczt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.miasto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.poczta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ulica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nrdomu)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.rabat)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.odbiorca_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.odbiorca_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.odbiorca_id })
        </td>
    </tr>
}

</table>